.gitignore
README.md
package-lock.json
package.json

https://github.com/ijmbarr/jupyterlab_spellchecker/issues/2

Updated package to work with jupyterlab version 0.32

---

README.md
package-lock.json
package.json
src/index.ts
src/svg.d.ts
style/icons/LICENSE
style/icons/ic-baseline-spellcheck.svg

Added spellcheck suggestions. Work fine with both notebook and file editor. Closes #16.

Implement suggestions support

---

package.json
schema/plugin.json
src/index.ts
style/icons/ic-baseline-spellcheck.svg

Version 0.1.8

---

README.md
schema/plugin.json
src/index.ts

This addresses #30, allowing users to easily change the MIME types for file editors.

Allow to easily change accepted MIME types

---

.eslintignore
.eslintrc.js
.github/workflows/build.yml
.gitignore
.prettierignore
.prettierrc
LICENSE
package.json
style/index.js

The results of following https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#jupyterlab-2-x-to-3-x
Note: not currently supporting installing via pip or conda. 
Fixes #43

Upgrading to work with jupyterlab v3.

---

src/index.ts

Hotfix after addition of federated extension in #48.
See https://github.com/jupyterlab/jupyterlab/issues/9124

Fix registration of CodeMirror mode for federated extension

---

schema/plugin.json
src/index.ts
style/index.css

Add themes with wavy and dotted underline

---

README.md
package.json

Update URLs after repo rename

---

.gitignore
CHANGELOG.md
package.json
src/index.ts

Added changelog to help users learn about new features and chages.

Release v0.5.0

---

.github/workflows/publish.yml
package.json

The python package got published, but the source extension did not make it to the NPM. Hopefully this would fix it.

Try to fix the publication script (v0.5.1)

---

yarn.lock

Pre-emptive upgrade for future

Perform a full yarn.lock upgrade

---

CHANGELOG.md
src/index.ts

implementing the feature from issue #61

Change the status message while loading a dictionary

---

CHANGELOG.md
package.json

Release v0.5.2

---

README.md

Finally managed to set us up on conda (https://github.com/conda-forge/jupyterlab-spellchecker-feedstock). Feel welcome to add yourself as a maintainer with a PR.

Add conda install instructions and version badges

---

.gitignore
CHANGELOG.md
jupyter-config/jupyter_notebook_config.d/jupyterlab_spellchecker.json
jupyter-config/jupyter_server_config.d/jupyterlab_spellchecker.json
jupyterlab_spellchecker/__init__.py
jupyterlab_spellchecker/dictionaries.py
jupyterlab_spellchecker/handlers.py
package.json
setup.py
src/handler.ts
src/index.ts

Changing the loading strategy from internal webpack loading to a free customisable  server extension solution.
Closes #69.
Closes #66.

- change dict loading mechanism from internal static to server extension

---

.github/workflows/build.yml
.github/workflows/publish.yml
src/index.ts

Fix dictionary selector

---

package.json
src/index.ts
yarn.lock

Adds support for translations of user-facing strings.

Add translation support

---

README.md
package.json
schema/plugin.json
src/index.ts

Implement online dictionaries

---

schema/plugin.json
tsconfig.json

- enable strict null checks, switch to modern compilation targets;
- add more Jupyter projects to spellcheck ignore

Update tsconfig settings and expand list of Jupyter projects in defaults

---

setup.py

See https://github.com/jupyterlab/jupyterlab/pull/10731

Add new trove classifiers

---

CHANGELOG.md
package.json

Dependency bump and addition of PyPI trove classifiers, no changes to the add-on itself.

Prepare release 0.7.1

---

schema/plugin.json

It probably makes sense to include IPython in the ignore list.

Add `IPython` to ignore list

---

package.json
yarn.lock

Bump version in preparation for release

Bump version and builder dev dependency

---

CHANGELOG.md
jupyterlab_spellchecker/__init__.py
package.json

Fixes an issue with 0.8.1 version

Hard-code `dest` to fix server extension loading
